name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Install Newman report 
      run: npm install newman-reporter-html 
      
    - name: Install Newman report htmlextra
      run: npm install -g newman-reporter-htmlextra

    - name: Run Newman
      run: newman run JSONPlaceholderAPI.postman_collection.json -r html --reporter-html-export newman-report.html

    - name: Publish Report
      uses: actions/upload-artifact@v2
      with:
        name: newman-report
        path: newman-report.html

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        branch: gh-pages
        folder: .


